# Book settings
title: Juliaで学ぶ計算論的神経科学
author: Yamamoto Takuto
logo: _static/images/logo.svg

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/compneuro-julia/compneuro-julia.github.io
html:
  use_repository_button: true
  use_issues_button: true
